### ISSUE TITLE
Incapable de faire fonctionner...

### ISSUE THREAD

**Issue by tardich** [MichelJourdain/Hydro-Quebec#4]
J'ai suivi l'installation à la lettre (enfin, je crois):

- Installer Swiss Army Knife custom card à partir de HACS
- Installer Decluttering Card à partir de HACS (en regardant la doc de Swiss Army....)
- Configurer Swiss Army Knife custom card (step 2)
- Ajouter la ressource Decluttering Card
- Installer vertical-stack-in-card à partir de HACS
- Installer Apexcharts-cards à partir de HACS
- Copier les templates requis dans /config/lovelace/sak_templates/templates/layouts
- Copier le theme dans /config/themes
- Copier HqCombo.yaml dans /config
- Ajouter les sensors requis dans sensor.yaml
- Redémarrer Home-Assistant

Et puis....  plus rien. Il me manque évidemment quelques étapes qui ne sont pas documentées...

**Comment by tardich** [comment]
Bon, j'ai retiré Décluttering de la liste. créant une carte pour Hydro-Québec dans mon dashboard, j'ai eu une erreur à l'effet que tabbed-card n'était pas reconnu. Il faudrait donc, dans la documentation, ajouter tabbed-card à installer par HACS. Mais maintenant, j'ai le problème suivant qui fait surface, et mes recherches ne donnent, à ce moment, aucun résultat:

i.setConfig is not a function.

J'ai cette erreur à chaque carte qui est créée (cartes de type custom: swiss-army-knife-card)

**Comment by MichelJourdain** [comment]
Ok, j’ai ajouté l’instruction pour la Tabbed Card. 

Malheureusement, vous avez le problème que plusieurs personnes ont et que, pour l’instant, ne semble pas avoir le solution. 

https://github.com/AmoebeLabs/swiss-army-knife-card/issues/237

En attendant une solution, si vous le désirez, vous pouvez utiliser cette page:

![image](https://github.com/MichelJourdain/Hydro-Quebec/assets/83040228/0f7513f8-54ad-491f-a74f-a8d770d7bd95)

https://github.com/MichelJourdain/Tableaux-De-Bords/blob/main/Mon-Tableau-De-Bord-V2/Vues/Vue-Hydro-Quebec-V2.yaml

**Comment by tardich** [comment]
Mieux que rien. Il me reste à figurer certains éléments à aller chercher, mais j'ai au moins une idée. En attendant mieux...  Merci

**Comment by tardich** [comment]
Il n'y a apparemment aucun progrès du côté de SwissArmyKnife (aucun mouvement depuis septembre 2023). Est-ce encore une option fiable pour le dashboard HydroQuébec (ou tout autre dashboard, en fait... même les démos ne fonctionnent plus)

**Comment by MichelJourdain** [comment]
Salut,

Effectivement, depuis le problème **i.setConfig is not a function**, le dévelopeur qui n’a pas trouvé de solution et n’a pas  reçu une réponse pour savoir comment corriger le problème, semble avoir abandonné. Dû moins pas de nouvelles de lui. 😟 De mon côté, j’ai refait un nouveau tableau de bord qui ne contient pas ces cartes. Je garde le vieux en réserve au cas où. C’est désolent car on pouvais créer de très belles cartes.

**Comment by tardich** [comment]
Est-ce que le nouveau tableau est publiable?

**Comment by MichelJourdain** [comment]
Salut,

Voici à quoi il ressemble. Notez que J’utilises le thème HA LCARS pour mon nouveau tableau.  Si ça vous intéresse, je peux publier mon code.

![IMG_8604](https://github.com/MichelJourdain/Hydro-Quebec/assets/83040228/7d0c082e-a599-4197-bc58-01fd6cc99a3a)

![IMG_8605](https://github.com/MichelJourdain/Hydro-Quebec/assets/83040228/36694b30-39d0-4c85-b431-4c0a6695a4b5)

![IMG_8603](https://github.com/MichelJourdain/Hydro-Quebec/assets/83040228/bef79561-97b0-4bdd-9cd2-7894508b91e2)

**Comment by tardich** [comment]
Ah oui, ça m'intéresse

**Comment by MichelJourdain** [comment]
Voilà, si vous avez des questions, ne vous gêné pas.

https://github.com/MichelJourdain/HQuebec

**Comment by tardich** [comment]
Hier soir, j'ai travaillé avec un collègue et réussi à refaire marcher le dashboard avec SwissArmyKnife. Je me propose de me spinner un HA flambant neuf et installer les morceaux nécessaires au dashboard pour comprendre exactement ce qui manque. J'en ferai une liste exhaustive ici. D'après ce que je comprend, l'installation de SwissArmyKnife est déficiente (autant en installation HACS qu'en installation manuelle).

Il y a de l'espoir !  :-)

**Comment by MichelJourdain** [comment]
Salut,

Effectivement, ça serait très intéressant si vous trouver une solution. Si vous trouvez on va la partager avec les autres qui ont le même problème que vous. Comme moi, je n’ai pas ce problème, c’est difficile pour moi de trouver la solution. J’ai vu que vous avez accepter le PR que je vous avais fait, es-ce que cela a fonctionné pour l’autre version?

**Comment by tardich** [comment]
Oui, ça a marché. Merci

**Comment by MichelJourdain** [comment]
Wow, je vais faire une traduction en Anglais et demander à une autre personne que je connais de faire le test. 

Merci,

**Comment by tardich** [comment]
Dans le setup testé, il est à noter que je n'ai ajouté aucun sensor puisque le test que j'avais à faire consistait à vérifier que les cartes loadaient, pas qu'elles contenaient les valeurs de certains sensors qu'il faut ajouter.

**Comment by MichelJourdain** [comment]
Pour moi c’est surtout la solution que vous avez trouver pour faire fonctionner SwissArmyKnife qui m’intéresse. D’un autre côté, j’ai migré mon instance HA sur un RPI 5 au début du mois de mars et j’ai décidé de repartir à zéro, pour faire du ménage. J’ai suivis les instructions d’installation et je n’ai pas eu de problème. Tout fonctionne pour les cartes SwissArmyKnife, ????

**Comment by tardich** [comment]
Oui, sans aucun problèmes

**Comment by MichelJourdain** [comment]
J’ai publié votre solution ici https://community.home-assistant.io/t/lovelace-versatile-swiss-army-knife-custom-card/432419/323 et ici https://github.com/AmoebeLabs/swiss-army-knife-card/issues/237 mais je n’ai pas eu de retour, donc impossible de valider si votre solution peu être appliquer par d’autres. Si ça fonctionne pour vous tant mieux.

**Comment by MichelJourdain** [comment]
Le problème est résolu pour vous. Aucun autre intervention après la publication de votre solution.
