### ISSUE TITLE
Manque 2 sensors

### ISSUE THREAD

**Issue by margag02** [MichelJourdain/Hydro-Quebec#5]
Bonjour, 

Excellent travail :)

Ma question est d'où vienne les 2 sensors "maison_number_of_winter_days" et "maison_number_of_critical_hours" ils sont toujours à 'Unknow"

**Comment by MichelJourdain** [comment]
Salut, 

Avez-vous le tarif FlexD? C’est deux sensors sont créé par le Add-on Hydroqc.

**Comment by margag02** [comment]
Non seulement les crédits hivernaux.   Donc cela explique le pourquoi.  Merci

**Comment by MichelJourdain** [comment]
Vous devriez utiliser celui si: https://github.com/MichelJourdain/Hydro-Quebec/tree/main/CreditHivernal

**Comment by margag02** [comment]
Merci beaucoup et encore une fois excellent travail :)

**Comment by margag02** [comment]
Merci
